const filmGenresAndSubgenres = {
  Action: [
    "Disaster",
    "Heroic Bloodshed",
    "Martial Arts",
    "Spy",
    "Superhero",
    "War",
  ],
  Adventure: ["Pirate", "Swashbuckler", "Samurai"],
  Animated: [
    "CGI",
    "Cutout",
    "Live-action",
    "Stop Motion",
    "Claymation",
    "Traditional",
  ],
  Comedy: [
    "Action Comedy",
    "Buddy",
    "Dark/Black",
    "Mockumentary",
    "Parody",
    "Romantic",
    "Screwball",
    "Slapstick",
  ],
  Drama: [
    "Docudrama",
    "Legal",
    "Medical",
    "Melodrama",
    "Political",
    "Psychological",
    "Teen",
  ],
  Fantasy: ["Contemporary", "Dark", "High/Epic", "Urban"],
  Historical: [
    "Alternate History",
    "Biopic",
    "Epic",
    "Historical Event",
    "Historical Fiction",
    "Period Piece",
  ],
  Horror: [
    "Found Footage",
    "Ghost",
    "Monster",
    "Slasher",
    "Splatter",
    "Zombie",
    "Supernatural",
  ],
  Musical: ["Jukebox"],
  Noir: ["Neo-noir", "Horror-noir", "Tech-noir"],
  Romance: [
    "Historical",
    "Paranormal",
    "Romantic Comedy",
    "Fantasy",
    "Thriller",
  ],
  ScienceFiction: [
    "Dystopian",
    "Post-apocalyptic",
    "Military",
    "Steampunk",
    "Tech noir",
    "Utopian",
    "Space Opera",
  ],
  Thriller: ["Psychological", "Mystery", "Techno", "Political"],
  Western: ["Epic", "Revisionist", "Spaghetti"],
};

export default filmGenresAndSubgenres;
